Resources:
  ConfigAutomationIamConstructtestSsmAutomationRole6553CA7A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonSSMAutomationRole
      RoleName: TestSsmAutomationRole
  RestrictedSSHConstructRestrictedSSHRuleE47565C4:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: RestrictedSSHRule
      InputParameters:
        blockedPort1: 22
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
  RestrictedSSHConstructRestrictedSSHRuleRemediation8832934D:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      Automatic: false
      ConfigRuleName:
        Ref: RestrictedSSHConstructRestrictedSSHRuleE47565C4
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 2
          ErrorPercentage: 5
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - Fn::GetAtt:
                  - ConfigAutomationIamConstructtestSsmAutomationRole6553CA7A
                  - Arn
        SecurityGroupId:
          ResourceValue:
            Value: RESOURCE_ID
      TargetId: AWS-CloseSecurityGroup
      TargetType: SSM_DOCUMENT
  RestrictedRDPConstructRestrictedRDPRuleF3896F27:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: RestrictedRDPRule
      InputParameters:
        blockedPort1: 3389
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
  RestrictedRDPConstructRestrictedRDPRuleRemediationC418DC7F:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      Automatic: false
      ConfigRuleName:
        Ref: RestrictedRDPConstructRestrictedRDPRuleF3896F27
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 2
          ErrorPercentage: 5
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - Fn::GetAtt:
                  - ConfigAutomationIamConstructtestSsmAutomationRole6553CA7A
                  - Arn
        SecurityGroupId:
          ResourceValue:
            Value: RESOURCE_ID
      TargetId: AWS-CloseSecurityGroup
      TargetType: SSM_DOCUMENT
  RestrictedCommonPortsConstructRestrictedCommonPortsRule1568EFD7:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: RestrictedCommonPortsRule
      InputParameters:
        blockedPort1: 20
        blockedPort2: 21
        blockedPort3: 3306
        blockedPort4: 4333
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
  RestrictedCommonPortsConstructRestrictedCommonPortsRuleRemediationD41A0B5C:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      Automatic: false
      ConfigRuleName:
        Ref: RestrictedCommonPortsConstructRestrictedCommonPortsRule1568EFD7
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 2
          ErrorPercentage: 5
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - Fn::GetAtt:
                  - ConfigAutomationIamConstructtestSsmAutomationRole6553CA7A
                  - Arn
        SecurityGroupId:
          ResourceValue:
            Value: RESOURCE_ID
      TargetId: AWS-CloseSecurityGroup
      TargetType: SSM_DOCUMENT
  RdsSnapshotsPublicProhibitedConstructRdsSnapshotsPublicProhibitedRuleBF90DDEE:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: RdsSnapshotsPublicProhibitedRule
      Source:
        Owner: AWS
        SourceIdentifier: RDS_SNAPSHOTS_PUBLIC_PROHIBITED
  RdsSnapshotsPublicProhibitedConstructRdsSnapshotsPublicProhibitedRuleRemediationF360928D:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      Automatic: false
      ConfigRuleName:
        Ref: RdsSnapshotsPublicProhibitedConstructRdsSnapshotsPublicProhibitedRuleBF90DDEE
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 2
          ErrorPercentage: 5
      Parameters:
        SnapshotIdentifiers:
          ResourceValue:
            Value: RESOURCE_ID
        Private:
          StaticValue:
            Values:
              - 'Yes'
        AutomationAssumeRole:
          StaticValue:
            Values:
              - Fn::GetAtt:
                  - ConfigAutomationIamConstructtestSsmAutomationRole6553CA7A
                  - Arn
        AccountIds:
          StaticValue:
            Values: []
        AccountPermissionOperation:
          StaticValue:
            Values: []
      TargetId: AWSSupport-ModifyRDSSnapshotPermission
      TargetType: SSM_DOCUMENT
Parameters:
  EnableAutomaticRepaier:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
